### ISSUE TITLE
robe does not support completion from installed Gems

### ISSUE THREAD

**Issue by stardiviner** [dgutov/robe#82]
I have code like this:

```ruby
require 'rubygems'
require 'mechanize'

agent = Mechanize.new
```
But robe can't complete for `Mechanize` methods.

**Comment by dgutov** [comment]
Is Mechanise loaded in the REPL buffer?

**Comment by stardiviner** [comment]
At first I press `[C-x C-e]` (`ruby-send-last-sexp`) to evaluate the `require 'mechanize'`.
Then I checked out `*rails*` repl buffer, see the output:

```
Running via Spring preloader in process 32700
Loading development environment (Rails 4.2.5.1)
irb(main):001:0> "robe on 34502"
irb(main):002:0> 
irb(main):007:0' irb(main):008:0' "mechanize"
```

After you asked question, I tried to input `require 'mechanize'` manually in `*rails*` repl buffer.
But got error:
```
irb(main):129:0> require 'mechanize'
LoadError: cannot load such file -- mechanize
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from (irb):129
	from /home/stardiviner/.gem/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/stardiviner/Code/learning/Ruby/Rails/learning/blog/bin/rails:9:in `<top (required)>'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/stardiviner/.gem/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/stardiviner/.rbenv/versions/2.3.0-dev/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by dgutov** [comment]
> At first I press [C-x C-e] (ruby-send-last-sexp) to evaluate the require 'mechanize'

The "last sexp" is the string `'mechanize'` in this case. Try `ruby-send-region` next time.

> LoadError: cannot load such file -- mechanize

You'll need to fix this in your setup.

> Is this because my installed gems are not in Emacs find path?

There is no "Emacs find path", it's all Ruby. Is `mechanize` in that project's `Gemfile`?

**Comment by stardiviner** [comment]
`mechanize` is'nt in my `Gemfile`.

I use `rbenv` to manage Ruby version. I enable one installed Ruby version.
I tried google for "Emacs inf-ruby rbenv gem not available". But no result.
Do you know how to fix this?

**Comment by dgutov** [comment]
Aw hell. What's this rbenv talk?

Put `mechanize` into your `Gemfile`. Then read about Bundler, what it does, and how.

**Comment by stardiviner** [comment]
Oh, sorry, I misunderstand `rbenv.el`. :>
