### ISSUE TITLE
Error finding bundler

### ISSUE THREAD

**Issue by Immortalin** [dgutov/robe#95]
Stacktrace:

```Ruby
/home/immortalin/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 11 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/immortalin/.gem/ruby/2.3.0:/home/immortalin/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /home/immortalin/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /home/immortalin/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /home/immortalin/.gem/ruby/2.3.1/bin/bundle:22:in `<main>'

Process ruby exited abnormally with code 1
```

**Comment by dgutov** [comment]
That's not a Robe problem. It's a Ruby+Emacs configuration problem.
